### ISSUE TITLE
RobotoA2 needs XTSB

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#10]
https://github.com/googlefonts/roboto-flex-avar2/tree/main/Source/Parametric%20avar2

We have a spacing axe for Roboto but no sources are in place or are they in the designspace file.

**Comment by gferreira** [comment]
XTSP :) I can do it, using the tight/loose spacing states from [Roboto Flex SPAC](http://github.com/googlefonts/roboto-flex-spacing-axis-demo).

**Comment by sannorozco** [comment]
I’m almost finish this @gferreira, I copied side bearings & kerning info from your sources and made new ones, since we updated them a lot. I’m checking all the accents positioning right now.

I can post heme and see If aI missed something?

**Comment by gferreira** [comment]
@sannorozco ok, thanks! you can go ahead and commit, I'll have a second look.

**Comment by sannorozco** [comment]
Added XTSP sources & axis. If you can take a look, we can talk tomorrow @gferreira?
