### ISSUE TITLE
Glyphs "Stenciling"

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#17]
Please check overlaps to ensure central location parallel to the stem they are overlapping, as they are separating and forming gaps.
Below on right end.
<img width="1060" alt="Screenshot 2024-01-17 at 8 28 36 AM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/814e43e8-4b08-4441-a455-d84c01283e82">
Left and second from left
<img width="1012" alt="Screenshot 2024-01-17 at 8 28 19 AM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/e169b89b-c3de-42fc-9d1a-637d2d26dd92">
two on the left one on the right
<img width="1009" alt="Screenshot 2024-01-17 at 8 27 48 AM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/473edef0-1fb5-4ee6-bab0-7b434ccf3536">
r, m and other too, all the way through the glyphs, please check all.

**Comment by sannorozco** [comment]
This has been fixed.
