### ISSUE TITLE
TechAlpha designspace/sources

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#2]
Installed:
https://github.com/googlefonts/roboto-flex-avar2/blob/main/Source/TechAlpha/sources/RobotoFlex.designspace
in Fontra, these axes appear to be changing Y trans and should not;
XOPQ
SPAC
XTRA
XTUC

**Comment by gferreira** [comment]
I've removed some of the parametric axes for now, which I think were causing errors: XOUC XOLC XOFI XTUC XTLC XTFI

the ones you mention above seem to be working correctly now. (currently in my working files, see pull request #4)

**Comment by dberlow** [comment]
These will probably be needed to separated out from their mother, XOPQ and XTRA, into the six child axes, no big deal right now as long as the mother axes work.On Oct 13, 2023, at 7:12 AM, Gustavo Ferreira ***@***.***> wrote:﻿
I've removed some of the parametric axes for now, which I think were causing errors: XOUC XOLC XOFI XTUC XTLC XTFI
the ones you mention above seem to be working correctly now. (currently in my working files, see pull request #4)

**Comment by davelab6** [comment]
@sannorozco can this be closed?
