### ISSUE TITLE
For testing and instruction on avar2 making, Google requests…

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#25]
…A json file with the blend values for our prototype designspace including all default sizes,, “sides and “corners”.

For each size master, there are an addition four sides and four corners, ie. 9 locations per size.
There are three size masters.
That’s 27 locations.

Please make such a file and let me know if there are any ?

**Comment by davelab6** [comment]
@sannorozco is this completed with c4773574cdab3b6e87c2d2bfad7e119c6d139909 ?

**Comment by sannorozco** [comment]
@davelab6 Let me make one more commit.

**Comment by sannorozco** [comment]
This is completed now.
