### ISSUE TITLE
Increasing range of XTRA max

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#27]
If you have your own proportonal, stem-protecting widener let me know.

Otherwise the goal would be to set up a mini-designspace with three corners extrapolating the fourth depending on the slightness factor but if its beyond that, the below variable procedure;

blend an instance of the regular that's is 130% e.g. a value larger than the needed extension.
this forms the third side with:
a. default
b. current XTRA max
c. 130% wdth 
d. if c contains significant changes to YOPQ or XOPQ, then add those axes to the mini designspace, and use them to alter the extrapolation of the new XTRA max to match the YOPQ and XOPQ of the previous XTRA max
e. Extrapolated and adjusted XTRA is the new XTRA max

**Comment by dberlow** [comment]
Example: Left, new. Right, old.
<img width="1810" alt="New:Old XTRA max (e g )" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/ce13131b-8e05-41f9-8796-e1cfa0c67234">

**Comment by sannorozco** [comment]
We needed to go beyond 130%, I generated the new XTRA and I’m not adjusting some shapes.

After this new XTRA I’ll need to remap all locations since they used the old XTRA.

Updating all this soon.

**Comment by sannorozco** [comment]
XTRA range increased.
