### ISSUE TITLE
Reviewing full designspace

### ISSUE THREAD

**Issue by sannorozco** [googlefonts/roboto-flex-avar2#28]
There are some issues in the blended locations on opsz144 , that need to be updated.

**Comment by dberlow** [comment]
Example:
left RobotoFlex 144, 100, 800. right RobotAvar2 144, 100, 800
<img width="2456" alt="Avar1 vs 2 144 100 800" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/0bf7aa04-a3d4-485b-9f7f-588ef389c146">

**Comment by davelab6** [comment]
@sannorozco can this be closed?

**Comment by sannorozco** [comment]
Yes, we’re working now in the full designspace.
