### ISSUE TITLE
Fencing in Giza: En guard!

### ISSUE THREAD

**Issue by davelab6** [googlefonts/roboto-flex-avar2#29]
Can avar2 fencing create a functional upside down pyramid, such that width 75% is always actually 75% of regular, and 25% is mostly fenced off except where large opsz segments of the design space cuboid allow it to really occur visually?

**Comment by behdad** [comment]
I believe that's not a problem. @Lorp ?

**Comment by Lorp** [comment]
It sounds fine to me, though forgive me if the mappings don’t come immediately to mind.

The way I think of it is that as long as there is "pressure in the pump" (meaning we are not at default), that pressure can be distributed around the system at will.

**Comment by davelab6** [comment]
Thanks @dberlow - agreed, we still have that to do, which is why I filed this issue :) 

> the UI, e.g. would need to broaden the available UI values of wdth axis as the opsz slider-ed up, and narrow the available UI values on the wdth axis sliding down in opsz

Currently UIs will not change the area the slider can travel within, but I believe that will be possible for future UIs without a file format spec change. Currently the UIs will allow the slider to travel in the ['phantom zones'](https://en.wikipedia.org/wiki/Phantom_Zone) fenced off, but nothing will happen to the type, ie, no deltas are applied.

Which UI should be used to pilot such an update? :) 

Calibrating wght is indeed a step up in challenge from calibrating wdth. But will it be OK to leave that until wdth is demo'd?

**Comment by Lorp** [comment]
I’m all for innovation in variable font UI, but we should be wary of restricting movement in any axis from the user’s perspective.

Consider a simple case of variable Univers with wght and wdth axes, where you use avar2 to prevent behind-the-scenes access to designspace locations around wght=max, wdth=min (i.e. you don’t want to allow Black Extra Condensed and the area near it). So it’s up to the avar2 engineer to decide how to remap that rejected rectangular area: maybe force wght to decrease, maybe force wdth to increase, maybe something more complex. So far so good.

But with a "restrictor" slider UI it soon gets confusing for the user if axis sliders are ever denied full freedom. When setting a new designspace location, the user would have to be careful about the order in which sliders are adjusted. You could easily get a situation where the current multidimensional location does not allow a given axis to be at max, yet at the intended multidimensional location it is fine for that axis to be at max. In this case, the user will be frustrated in having to configure other axes before the given axis can be moved to max.

Furthermore, while it might initially appear easy enough to work out the restricted zones of input axes by looking at designspace source, in general avar2 maths does not allow such regions to be determined.

**Comment by davelab6** [comment]
@sannorozco can this be closed?

**Comment by sannorozco** [comment]
Yes, this will be covered by the UI.
