### ISSUE TITLE
Tse glyph

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#37]
Fontra is rejecting the Tse for some reason. 

I have been though the sources I'm working on, and all the non-slant-related sources, and have found no incompatibilities.

<img width="578" alt="Tse" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/9873fc83-3e2b-4534-add5-80497370d1f2">

**Comment by sannorozco** [comment]
I see it on Chrome and Safari, I’m using the latest Fontra build.

<img width="1046" alt="Screenshot 2024-04-24 at 17 31 03" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1184152/a477ee08-446a-42c1-91a3-4e0f1173e43f">

<img width="1013" alt="Screenshot 2024-04-24 at 17 31 44" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1184152/56eaa2b7-3b74-409c-8e22-9998ec9a9899">

**Comment by Bronnel721** [comment]
> I see it on Chrome and Safari, I’m using the latest Fontra build.
> 
> <img alt="Screenshot 2024-04-24 at 17 31 03" width="1046" src="https://private-user-images.githubusercontent.com/1184152/325420164-a477ee08-446a-42c1-91a3-4e0f1173e43f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY0NDY3NTksIm5iZiI6MTc3NjQ0NjQ1OSwicGF0aCI6Ii8xMTg0MTUyLzMyNTQyMDE2NC1hNDc3ZWUwOC00NDZhLTQyYzEtOTFhMy00ZTBmMTE3M2U0M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MTdUMTcyMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjY0ZWMyZDI1ZmQzNDk5MjEzMGZmZmEyYzQwMGUzY2VhZDFlYWZiMjZlZTNjZDFlNGRhMWY4NDVlNmE3NzIzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.1ZN8itJ2MBV6-KhbmfYRkM9sbIl5DtYzOKwneqh9brI"> <img alt="Screenshot 2024-04-24 at 17 31 44" width="1013" src="https://private-user-images.githubusercontent.com/1184152/325420168-56eaa2b7-3b74-409c-8e22-9998ec9a9899.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY0NDY3NTksIm5iZiI6MTc3NjQ0NjQ1OSwicGF0aCI6Ii8xMTg0MTUyLzMyNTQyMDE2OC01NmVhYTJiNy0zYjc0LTQwOWMtOGUyMi05OTk4ZWM5YTk4OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MTdUMTcyMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2JmZjZlZGQ5N2EzYWM2NzM3OWFjZTNhMjE2OGQ3NTNlMWUyNjU2YTE5OTAyN2Y5M2E3Njg1ZGE4OWIxOTIzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.YxwbF-J34BUiM35QnDdvNdjLV16Dj62CYLqYjEqPTI8">

It doesn't have a Unicode codepoint for it though:

<img width="667" height="339" alt="Image" src="https://github.com/user-attachments/assets/0f16526c-38d3-4b10-a196-27c56da0b291" />
(this image was taken in Windows 11 using Google Chrome if you're wondering)
