### ISSUE TITLE
RobotoA2-avar2-fences-VF.ttf opsz 144 wght axis intermediate at 600, and other persisting interpolation issues

### ISSUE THREAD

**Issue by davelab6** [googlefonts/roboto-flex-avar2#42]
Now that its May, I grabbed the latest RobotoA2-avar2-fences-VF.ttf ([permalink](https://github.com/googlefonts/roboto-flex-avar2/blob/041c4e482d641ad0efdf358ddd2d09feb322718f/fonts/LGCAlpha/RobotoA2-avar2-fences-VF.ttf)) and looked at the opsz-144 weight progression, and found it to be curious - the 100 to 400 expands, then 400 to 600 contracts, then 600 to 1000 expands again. 

Here's the [TypeRoof test url](https://fontbureau.github.io/TypeRoof/#2024-05-03T23:12:30Z;RobotoAvar2%20Regular,Version%203.000;;;111;;01;5;0;opsz144,wght544;1;144;0;l;;0;opsz25;1;25;0;l;;0;opsz18;1;18;0;l;;0;opsz18;1;18;0;l;;0;wght100;1;14;0;l;;0;@v2:typespec) I used, and a screencap video:

![Kapture 2024-05-03 at 17 12 30](https://github.com/googlefonts/roboto-flex-avar2/assets/261579/c31f1daa-df9a-429c-8cbc-6e7904fdae46)

I guess there's an intermediate at 600 that's causing this; but, at this stage, based on recent calls with @dberlow, I am expecting the only intermediates to be at corners (like opsz 144, wght 100 and 1000), which he explained are expected to be there temporarily for debugging the parametric-axes constructed user-axes design space (opsz-wght-wdth-GRAD). 

Stepping back to the high level goals of this whole project, the primary goal is to **prove** that such a huge-area user-axes design space really can be constructed from parametric-axes only, such that there is zero gvar data for those axes (and thus zero instances.)

I understand from @dberlow he believes this will be possible, by either adjusting the already defined parametric axes, or by splitting out those axes into sets of glyph-reportoire-range specific ones that adjust specific parts of a range of glyphs; and that instances can help with debugging the parametric axes in that way.

However, I'm not sure what the effect of removing the 600 instance will be, but I suspect it will exacerbate the issues I can see with basic glyph integrity when interpolating 400..1000; the 400..600 range is working well, but 600..1000 and 100..400 have some issues. 

The only one I spotted with a non-systematic spot check of the 400 to 100 range is in the `e`, where the bar disconnects from the loop just a little bit:

<img width="1305" alt="Screenshot 2024-05-03 at 5 21 20 PM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/261579/02803daa-ee58-4e09-a4e3-aa2f55ce05f9">
<img width="1305" alt="Screenshot 2024-05-03 at 5 21 28 PM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/261579/d3f1480d-e306-4f14-b068-6228882f67a7">
<img width="1305" alt="Screenshot 2024-05-03 at 5 21 37 PM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/261579/82b48076-9bab-4424-9794-f41a027a7eb4">
<img width="1305" alt="Screenshot 2024-05-03 at 5 21 40 PM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/261579/34fe6b29-4a28-4580-b4c8-a9dd10abed5c">

In the 600..1000 range there are a lot of problems in a lot of glyphs with round strokes, where the off-curve points appear "double delta'd" and extended into the counter space on the insides, and make the outer edges too squarish; playing with the primary parametric axes, it seems the issue might be in YOPQ, but I leave it to you to figure out how to address it :)

<img width="1305" alt="Screenshot 2024-05-03 at 5 22 24 PM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/261579/3c7f1cb8-2644-4f76-b797-200ec3292384">
<img width="1305" alt="Screenshot 2024-05-03 at 5 22 41 PM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/261579/26fc5e4a-81c1-4b47-a8ce-8de3178df4ac">
<img width="1305" alt="Screenshot 2024-05-03 at 5 22 49 PM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/261579/fbd6e7ab-13e4-4521-88fa-ed8f7c094d04">

So, with the primary goal in mind, since we are now into May, I am wondering about the feasibility of completing an ASCII glyph set that is parametric-only; as an R&D project, I have no issue with reducing the glyph repertoire to the smallest set of 'key' glyphs that prove it is possible to make parametric-only gvars for the completely huge range of user-axes, and then moving up to demonstrate solutions to various known challenges, like the most key glyphs `OHno` and then challengers like `S$`, and then moving up and up to larger and larger glyph repertoires.

**Comment by sannorozco** [comment]
Hi,

On the weight progression, there is no instance at 144 600, we’ve noticed that before and the cause is that XTRA, XTSP move faster than XOPQ, so that looks like this. We fixed this by adding the weight mappings, [they where temporary in comments](https://github.com/googlefonts/roboto-flex-avar2/blob/041c4e482d641ad0efdf358ddd2d09feb322718f/Source/Parametric-avar2/RobotoAvar2-avar2-fences.designspace#L672-L813), now uncommented and weight range is smooth.

On the second issue about round shapes, I believe I know the issue, and will need to do some tests and talk with @dberlow.

**Comment by dberlow** [comment]
The issue about shapes is that the blends too far from the ideal, and are NOT interpolating to be close to the drawn instances.

So at 144 1000, we have a perfect style, but by 144 985 it's breaking, and broken by 980.
Below are 1000, 985 and 980.
<img width="759" alt="Screenshot 2024-05-06 at 8 52 34 AM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/c2dde03f-020a-4d6a-b2d8-df9e2e63b894">
<img width="849" alt="Screenshot 2024-05-06 at 8 52 56 AM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/a80200a1-37a0-4f79-97cf-7f9e3b40fa53">
<img width="848" alt="Screenshot 2024-05-06 at 8 53 14 AM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/8cc4a955-0ad0-43a4-8916-491bbe1f5875">

It seems to have weak interpolation powers, so the blend must be so close to the drawn instance, it is not worth adding it.

**Comment by davelab6** [comment]
Overall Weight progression is now good :)
