### ISSUE TITLE
Previous blend values in wght

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#43]
The former designspace file had the blend values listed below.
OS2 XOPQ x2  XTRA Sum
400   49       449    = 547
500   96      418     = 610
600  136      387    = 659
700   177     356.    = 710
800   218     325    = 679 
900 258.     294    = 810
1000 300.    262.   = 862 

OS/2 value is listed in column 1, 
XOPQ x2 means add two stem values to 
XTRA and 

Sum is the addition of two paramtric stems and a counter.  

I think the sum at wght 800 should have been 760.

**Comment by davelab6** [comment]
@sannorozco i believe this can be closed?
