### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/roboto-flex-avar2#50]
Hi! We tried to do a build in the project, but we failed. 

after several errors and several hacks, this is where we finished. can you help us??

`INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
fontmake: Error: In 'RobotoAvar2-avar2.designspace': Generating fonts from Designspace failed:

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation:
GSUB.table.LookupList.Lookup[0][0].BacktrackCoverage[0].glyphs[1]

The problem is likely to be in RobotoAvar2 741:
Expected to see [1]=='underscore', instead saw 'hyphen'`

**Comment by sannorozco** [comment]
Hallo @octaviopardo ,

It’s the glyph order, I just updated it, could you check please?

**Comment by octaviopardo** [comment]
Hi @sannorozco 
Top, we managed to build it. Congrats in the project, this is awesome

**Comment by sannorozco** [comment]
Awesome!

Thanks, It’s a team effort.

I’m closing this issue.
