### ISSUE TITLE
Font disappeared: fonts/LGCAlpha/RobotoA2-avar2-clean-VF.ttf

### ISSUE THREAD

**Issue by graphicore** [googlefonts/roboto-flex-avar2#52]
In commit c90e74139780be8d0ddb0c8f32b1b03728702484 the line that generates `fonts/LGCAlpha/RobotoA2-avar2-clean-VF.ttf` was removed. However, I was tasked to include that file into TypeRoof and look for updates/update it periodically. Now the [GitHub Workflow job that pulls updates of the font fails](https://github.com/FontBureau/TypeRoof/actions/runs/9778086385/job/26994139004). 

Is there a new font somewhere that I should include instead?

**Comment by sannorozco** [comment]
Hallo Lasse @graphicore!

Apologies, yes, I moved files and this is the new one we should point to now: fonts/LGCAlpha/RobotoA2-avar2-VF.ttf

This should fix the automatic pull for TypeRoof.

Let me know,

**Comment by graphicore** [comment]
Thanks @sannorozco, [it works](https://github.com/FontBureau/TypeRoof/actions/runs/9779899046)

**Comment by sannorozco** [comment]
Thank you @graphicore!
