### ISSUE TITLE
Host /docs/proof-robo-compare on github pages

### ISSUE THREAD

**Issue by davelab6** [googlefonts/roboto-flex-avar2#60]
I'd love to load https://github.com/googlefonts/roboto-flex-avar2/tree/main/docs/proof-robo-compare from this repo's github pages URL :)

**Comment by davelab6** [comment]
@sannorozco do you think you could sort this out in the coming week?

**Comment by sannorozco** [comment]
Of course! It will be sorted out 🙂.

**Comment by davelab6** [comment]
Try now :)

**Comment by davelab6** [comment]
I got impatient and got it working, but there's now a duplicate copy of `/fonts/LGCAlpha/RobotoA2-avar2-VF.ttf` in the `/docs/proof-robo-compare` folder; however the CSS has the original `../../` URL for local testing first, and if that isn't found, then it loads the copy. 

https://googlefonts.github.io/roboto-flex-avar2/proof-robo-compare/ loads as

<img width="1724" alt="Screenshot 2024-08-29 at 3 00 11 AM" src="https://github.com/user-attachments/assets/4de016cc-10a4-4120-9ac7-0648668f49fb">

and for me this at a glance looks fiendishly close :) 

Zooming in the opsz and showing the lowercase, I can start to see the differences:

<img width="1435" alt="Screenshot 2024-08-29 at 2 54 16 AM" src="https://github.com/user-attachments/assets/4bf5e813-386e-42bf-866f-528e27197084">

And at the corners, it seems to run tighter at the moment (which I guess will get even tighter with kerning?), which is good, except for wght-min, which seems to run a bit wider:

<img width="1721" alt="Screenshot 2024-08-29 at 3 02 55 AM" src="https://github.com/user-attachments/assets/0078f279-b324-42c1-8508-96416c2a69b2">

<img width="1716" alt="Screenshot 2024-08-29 at 3 02 42 AM" src="https://github.com/user-attachments/assets/77f3a916-6c7e-4a85-b6bf-5a99c0727c07">

<img width="1717" alt="Screenshot 2024-08-29 at 3 02 30 AM" src="https://github.com/user-attachments/assets/ea438bc7-257d-4f18-a94d-595a40b67c31">

<img width="1717" alt="Screenshot 2024-08-29 at 3 01 53 AM" src="https://github.com/user-attachments/assets/fb8d7447-62b9-4807-8ed9-ad89260ea238">

<img width="1715" alt="Screenshot 2024-08-29 at 3 02 07 AM" src="https://github.com/user-attachments/assets/79e874d3-970c-42ba-8e12-57d02a3e265a">

But wow, you guys _have had it in you to make it epic_ :)
