### ISSUE TITLE
Bowl and Arch joins along wght at opsz-max wdth-def 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/roboto-flex-avar2#61]
Chatting with @simoncozens he pointed out how the Bowl and Arch joins along the wght axis at opsz-max wdth-def differ from the original statics,

<img width="1725" alt="Screenshot 2024-08-29 at 4 03 34 AM" src="https://github.com/user-attachments/assets/33d727d6-78c3-44dc-8b6f-a990fbea7b7c">
<img width="1725" alt="Screenshot 2024-08-29 at 4 05 06 AM" src="https://github.com/user-attachments/assets/d37735ea-4f26-4b33-930c-4796bb54253d">

and A1 and A2

<img width="1725" alt="Screenshot 2024-08-29 at 4 03 12 AM" src="https://github.com/user-attachments/assets/dae748ac-5964-4391-b757-bbb03f6c78fe">

<img width="1725" alt="Screenshot 2024-08-29 at 4 03 03 AM" src="https://github.com/user-attachments/assets/9b5f7ce3-bd41-4f5f-bf6c-7ae400f081f9">

It seems the A1 kept the flat bowl joins in the wght min and made them much more oval in the wght max, and A2 reverses this. 

I wonder if it is possible for the A2 to be flat at the wght min too. 

Similarly for the arch joins in /n/m, the original statics seem half way between A1 (higher) and A2 (lower). I wonder if it is possible for the A2 to be less deep there.

I thihnk there is just a little too much stroke contrast in A2, at the moment, at the wght default 400, and 300 too:

<img width="1725" alt="Screenshot 2024-08-29 at 4 10 19 AM" src="https://github.com/user-attachments/assets/04c106cd-1b1d-4c1d-a16b-ce568bfcac3d">

<img width="1725" alt="Screenshot 2024-08-29 at 4 10 29 AM" src="https://github.com/user-attachments/assets/63e50486-b48c-48bf-ae80-c9cf74dc03d2">

**Comment by dberlow** [comment]
By "original statics", what exactly do you mean?

**Comment by sannorozco** [comment]
A2 144 weight min now has flat arc/shoulder joints at same height. That /m took me a while since there are many sources involved.

<img width="2370" alt="Screenshot 2024-09-03 at 12 48 39" src="https://github.com/user-attachments/assets/caf65617-1f4b-44c7-bf5f-d8a272fae37b">


<img width="2374" alt="Screenshot 2024-09-03 at 12 54 08" src="https://github.com/user-attachments/assets/95f7cefa-48ef-4805-adb1-6ae29b133bf6">

<img width="2371" alt="Screenshot 2024-09-03 at 12 53 33" src="https://github.com/user-attachments/assets/73e3e896-4caf-439c-b8cc-a7d14c53d86a">

**Comment by davelab6** [comment]
> By "original statics", what exactly do you mean?

The version of Roboto widely used for many years, and which is still being served on fonts.google.com today and in Workspace apps, before Font Bureau became involved in its development; which is what people think of when they think of "Roboto", and which the FB Roboto Classic VF is very close to.

> A2 144 weight min him bpdgq now has flat arc/shoulder joints at same height. That /m took me a while since there are many sources involved.

This looks much more "the same typeface" to me! Well done :)
