### ISSUE TITLE
Tech Alpha Test

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#9]
installed and tested: 

https://github.com/googlefonts/roboto-flex-avar2/blob/main/fonts/Tech%20Alpha%20TTFs/RobotoFlex0.ttf

please see test 
TextEdit file, (requires font install).
https://github.com/googlefonts/roboto-flex-avar2/blob/main/fonts/Tech%20Alpha%20TTFs/Tests/Roboto%20Avar2%20test%201.rtf

**Comment by gferreira** [comment]
`RobotoFlex1.ttf` is the one which includes avar2 blended axes – see [fonts/Tech Alpha TTFs/README.md](http://github.com/googlefonts/roboto-flex-avar2/blob/main/fonts/Tech%20Alpha%20TTFs/README.md) for a description of what each font file contains.

this avar2 font does not include instances yet. I'll build a new version which includes them.

**Comment by gferreira** [comment]
test font `fonts/Tech Alpha TTFs/RobotoFlex1.ttf` (avar2) now includes named instances, see 143a19e56ddc18910dcf7e963a43c550a4ab13d6.

I can install the font in FontBook; the named instaces show up in a menu, but the style locations are incorrect.

the font and its named instances do not show up in the font menu of TextEdit or Pages apps.

I've created a test page to compare avar1 and avar2 in the browser, see the file `index.html` inside the fonts folder. also there we can see that the avar2 font is not working as intended.

in the meantime I've also found this [avar2 test page](http://lorp.github.io/samsa/src/samsa-avar2.html) by @Lorp, which shows a working avar2 version of Amstelvar, but produces the same buggy results for the current `RobotoFlex1.ttf` font.

**Comment by gferreira2** [comment]
summary:

- we are trying to build avar2 fonts with blended axes
- the designspace file is created with `fontTools.designspaceLib.DesignSpaceDocument`
- the avar2 mappings are created with `AxisMappingDescriptor` (new in [5.1](http://fonttools.readthedocs.io/en/latest/designspaceLib/index.html#version-5-1))
- the variable font is built with `ufo2ft.compileVariableTTF`

the resulting font has *something* in terms of an avar2 table. but the font does not behave as expected when tested in native macOS apps, FontGoggles, or [avar2 test page](http://lorp.github.io/samsa/src/samsa-avar2.html).

@behdad can you provide an example of how to build an avar2 font from a designspace? I know of [generate-avar2](https://github.com/behdad/generate-avar2), but that seems to be older than the mappings syntax proposed [here](http://github.com/harfbuzz/boring-expansion-spec/blob/main/avar2-in-designspace.md#parametric-use-case). thanks in advance!

**Comment by schriftgestalt** [comment]
You can just use fontmake to generate fonts from the .designspace. Works fine out of the box. And FontGoggles can be used to preview it.

**Comment by Lorp** [comment]
Can you share your avar2 mappings? Maybe try to get one user axis working at a time.

**Comment by schriftgestalt** [comment]
I’ll prepare some.

**Comment by schriftgestalt** [comment]
That should give somehow working results. 
```
    <mappings>
      <mapping>
        <input>
          <dimension name="Optical size" xvalue="8"/>
        </input>
        <output>
          <dimension name="opsz" xvalue="8"/>
        </output>
      </mapping>
      <mapping>
        <input>
          <dimension name="Weight" xvalue="100"/>
        </input>
        <output>
          <dimension name="wght" xvalue="100"/>
        </output>
      </mapping>
      <mapping>
        <input>
          <dimension name="Weight" xvalue="1000"/>
        </input>
        <output>
          <dimension name="wght" xvalue="1000"/>
        </output>
      </mapping>
      <mapping>
        <input>
          <dimension name="Width" xvalue="25"/>
        </input>
        <output>
          <dimension name="wdth" xvalue="25"/>
        </output>
      </mapping>
      <mapping>
        <input>
          <dimension name="Width" xvalue="151"/>
        </input>
        <output>
          <dimension name="wdth" xvalue="151"/>
        </output>
      </mapping>
      <mapping>
        <input>
          <dimension name="Weight" xvalue="100"/>
          <dimension name="Grade" xvalue="-200"/>
        </input>
        <output>
          <dimension name="wght" xvalue="100"/>
          <dimension name="GRAD" xvalue="-200"/>
        </output>
      </mapping>
    </mappings>
```

**Comment by gferreira** [comment]
we have managed to build avar2 fonts in the latest set of test fonts (AsciiAlpha). not sure what went wrong in the first attempt.

**Comment by behdad** [comment]
> @behdad can you provide an example of how to build an avar2 font from a designspace? I know of [generate-avar2](https://github.com/behdad/generate-avar2), but that seems to be older than the mappings syntax proposed [here](https://github.com/harfbuzz/boring-expansion-spec/blob/main/avar2-in-designspace.md#parametric-use-case). thanks in advance!

Sorry I missed this before. Take a look at this example:
https://github.com/fonttools/fonttools/blob/main/Tests/designspaceLib/data/test_avar2.designspace

**Comment by dberlow** [comment]
Gustavo, is this enough to go on?

**Comment by gferreira** [comment]
@behdad thanks for the example.

we've managed to build avar2 fonts using the [fontTools documentation](http://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#example-of-all-mappings-elements-together) as reference.

the challenge now is to implement fences for blended axes. I'll open a separate issue for that.

**Comment by davelab6** [comment]
@gferreira2 I suggest this issue can be closed now :)

**Comment by sannorozco** [comment]
@davelab6 Yes.
